---
title: "00_TimeSeries_Example"
author: "Simon Topp"
date: "11/11/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(trend)
library(stlplus)

knitr::opts_chunk$set(echo = TRUE)
```

## A couple quick plot examples

```{r cars}
jsFiltered <- read_csv("JLSDtotal.csv")

## Add time
jsFiltered <- jsFiltered %>%
  mutate(time = paste0(hour(time),':',minute(time),':',second(time)),
         time = hms(time))

## For these examples I'm just going to filter out values that don't make sense (>5 meters), but ultimately you should take a look and see what's up with those.
## Also, since we have a bunch of sites, lets just take the average daily value

jsFiltered <- jsFiltered %>% filter(secchidepth < 5) %>%
  group_by(date) %>%
  summarise(secchidepth = median(secchidepth)) %>%
  ungroup() %>%
  arrange(date)

## Try a non parametric trend test.
mk.test(jsFiltered$secchidepth)

#Look at the magnitude of that trend
sens.slope(jsFiltered$secchidepth)
# It says clarity has been increasing!  by 0.0005 m a day!

## Challenge....do the above but controlling for season (seasonal sen slope)

## Plot up the data over the years
jsFiltered %>%
  ggplot(aes(x = date, y = secchidepth)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  theme(legend.position = 'none')


## Group things by month to see if theres there's a seasonal signal
jsFiltered %>%
  mutate(month = month(date, label = T)) %>%
  ggplot(aes(x = month, y = secchidepth)) +
  geom_boxplot()
# Except for February (which might be wonky due to few observations) it totally looks like there is


### Total bonus, do a seasonal decomposition.  Here I use an approach called STL, Johnathon would give you big bonus points if you did a similar thing with a Fourier Transform.  Both do a similar thing where they extract the seasonal component and the overall trend, STL can just handle missing data whereas Fourier analysis doesn't (you'd have to impute the missing values)

## Also, take all this with a grain of salt, there's a lot of missing data here

## First summarize everything to a monthly value
jsMonthly <- jsFiltered %>%
  mutate(year = year(date), month = month(date)) %>%
  group_by(year,month) %>%
  summarise(secchi = median(secchidepth))

## We need to create a full time series where there is one row for every month for every year
full.ts <- expand.grid(year = seq(min(jsMonthly$year),max(jsMonthly$year),1),
                       month = c(1:12)) %>%
  arrange(year,month) %>%
  left_join(jsMonthly)

## This does the stl (more info at https://anomaly.io/seasonal-trend-decomposition-in-r/)
stl <- stlplus(full.ts$secchi, n.p = 12, s.window = 'periodic')

## Pull out the summary values from the resulting stl object and join them with the actual dates to replace the temesteps
ts.summary <- stl$data %>% select(raw, seasonal, trend, remainder) %>%
  bind_cols(full.ts %>% select(year,month)) %>%
  mutate(date = ymd(paste0(year,'-',month,'-01'))) %>%
  select(-year, -month) %>%
  pivot_longer(-date, values_to = 'Secchi', names_to = 'Component')

## Plot up the seasonal and trend parts.
ggplot(ts.summary, aes(x = date, y = Secchi)) +
  geom_line() +
  facet_wrap(~Component, ncol = 1, scales = 'free')

```
